from docx import Document

doc = Document()
doc.add_heading('RENTAL AGREEMENT', 0)
doc.add_paragraph('This Rental Agreement ("Agreement") is entered into on January 15, 2024, between:')
doc.add_paragraph('LANDLORD: Rajesh Kumar Singh')
doc.add_paragraph('Address: 123 MG Road, Bangalore, Karnataka 560001')
doc.add_paragraph('')
doc.add_paragraph('TENANT: Priya Sharma')
doc.add_paragraph('Address: 456 Residency Road, Bangalore, Karnataka 560025')
doc.add_paragraph('')
doc.add_heading('PROPERTY DETAILS:', 1)
doc.add_paragraph('The Landlord agrees to rent to the Tenant the residential property located at: Flat No. 402, Green Valley Apartments, Koramangala 4th Block, Bangalore 560034')
doc.add_heading('TERMS AND CONDITIONS:', 1)
doc.add_heading('1. LEASE PERIOD', 2)
doc.add_paragraph('The lease shall commence on February 1, 2024 and continue for a period of 11 months, ending on December 31, 2024.')
doc.add_heading('2. RENT', 2)
doc.add_paragraph('The monthly rent is Rs. 25,000 (Rupees Twenty-Five Thousand Only), payable on or before the 5th day of each month.')
doc.add_heading('3. SECURITY DEPOSIT', 2)
doc.add_paragraph('The Tenant shall pay a refundable security deposit of Rs. 75,000 (Rupees Seventy-Five Thousand Only) at the time of signing this agreement.')
doc.add_heading('4. MAINTENANCE', 2)
doc.add_paragraph('The Tenant shall be responsible for all utility bills including electricity, water, and internet charges.')
doc.add_heading('5. TERMINATION', 2)
doc.add_paragraph('Either party may terminate this agreement by providing 15 days written notice to the other party. Upon termination, the Tenant must vacate the premises immediately.')
doc.add_heading('6. DISPUTE RESOLUTION', 2)
doc.add_paragraph('Any disputes arising from this agreement shall be resolved through arbitration in Bangalore, Karnataka.')
doc.add_heading('7. MODIFICATIONS', 2)
doc.add_paragraph('The Landlord reserves the right to modify the terms of this agreement at any time without prior notice to the Tenant.')
doc.add_heading('8. LOCKS AND KEYS', 2)
doc.add_paragraph('The Landlord retains the right to enter the property at any time without prior notice for inspection or repairs.')
doc.add_paragraph('')
doc.add_paragraph('SIGNATURES:')
doc.add_paragraph('')
doc.add_paragraph('Landlord: _________________ Date: _________')
doc.add_paragraph('(Rajesh Kumar Singh)')
doc.add_paragraph('')
doc.add_paragraph('Tenant: _________________ Date: _________')
doc.add_paragraph('(Priya Sharma)')
doc.save('test_rental_contract.docx')
print('DOCX created successfully')
