"""
Explanation generation and citation formatting for ScanTract Stage 8.

Generates plain-language explanations for risk findings and formats
legal citations from traced references (no LLM hallucination).
"""

import re
from datetime import datetime
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession
import logging

from .llm_client import call_llm
from .models import ContractExplanationsResponse, RiskyClauseExplanation, MissingClauseExplanation
from ..db.models import RiskFinding, Clause

logger = logging.getLogger(__name__)


def parse_explanation(response_text: str) -> str | None:
    """
    Parse LLM response to extract plain-text explanation.
    
    Handles:
    - Plain text responses
    - JSON-wrapped responses with various key structures
    - Malformed JSON with trailing/leading fragments
    - Text in JSON keys (when value is empty/invalid)
    - Joins content from both keys (20+ chars) and values
    
    Args:
        response_text: Raw LLM response
    
    Returns:
        Cleaned explanation text or None if invalid
    """
    import json
    
    explanation = response_text.strip()
    
    # Reject if contains triple pipes (corruption indicator)
    if '|||' in explanation:
        logger.warning(f"Explanation contains '|||' corruption marker, rejecting")
        return None
    
    # Try to parse as JSON first
    if explanation.startswith('{'):
        try:
            parsed = json.loads(explanation)
            if isinstance(parsed, dict):
                # Collect content strings: keys >= 20 chars (after stripping) and all non-empty string values
                content_parts = []
                
                for key, value in parsed.items():
                    # Process key
                    if isinstance(key, str):
                        # Strip leading punctuation from key: ". ", ": ", etc.
                        key_stripped = re.sub(r'^["\.\s:]+', '', key).strip()
                        if len(key_stripped) >= 20:
                            content_parts.append(key_stripped)
                    
                    # Process value
                    if isinstance(value, str):
                        value_stripped = value.strip()
                        if value_stripped:  # Non-empty
                            content_parts.append(value_stripped)
                
                if content_parts:
                    explanation = ' '.join(content_parts)
                else:
                    # No valid content found
                    logger.warning(f"JSON dict has no valid string values or keys: {list(parsed.keys())}")
                    return None
        except json.JSONDecodeError:
            # If JSON parsing fails, strip malformed JSON artifacts
            # Remove leading JSON fragments: {, {"key":, {", etc.
            # Pattern: opening brace, optional quotes/keys/colons, optional whitespace
            explanation = re.sub(r'^\{\s*("[^"]*"\s*:\s*)?["\s]*', '', explanation)
            # Remove trailing JSON fragments: }, ", etc.
            explanation = re.sub(r'["\s]*\}\s*$', '', explanation)
            explanation = explanation.strip()
    
    # Also strip leading } for malformed responses
    explanation = explanation.lstrip('}').strip()
    
    # Strip leading punctuation fragments from malformed JSON keys: ". ", ": ", etc.
    explanation = re.sub(r'^["\.\s:]+', '', explanation)
    
    return explanation


def validate_explanation(explanation: str | None) -> bool:
    """
    Validate parsed explanation meets quality criteria.
    
    Args:
        explanation: Parsed explanation text
    
    Returns:
        True if valid, False otherwise
    """
    # Validate length - reject if too short, just braces/null, or over 2000 chars
    if not explanation or len(explanation.strip()) < 20 or len(explanation) > 2000 or explanation.strip() in ["{}", "null", "{\n\n}"]:
        return False
    return True


async def generate_explanation(
    finding: RiskFinding,
    db: AsyncSession
) -> str:
    """
    Generate plain-language explanation for a risk finding.
    
    Args:
        finding: RiskFinding from database
        db: Database session
    
    Returns:
        Plain-language explanation (2-4 sentences)
    
    Note:
        Citation is NOT generated by LLM - formatted separately
        from existing triggering_rule_or_corpus field.
    """
    # Build prompt for explanation
    prompt = _build_explanation_prompt(finding)
    
    # Call LLM (provider-agnostic via call_llm) - request plain text
    messages = [{"role": "user", "content": prompt}]
    response_text, tokens_used = await call_llm(messages, plain_text=True)
    
    # Parse and validate using extracted functions
    explanation = parse_explanation(response_text)
    
    if not validate_explanation(explanation):
        logger.warning(
            f"Generated explanation is invalid (len={len(explanation) if explanation else 0}): "
            f"'{explanation[:50] if explanation else 'None'}'"
        )
        # Don't cache invalid explanation, leave it NULL
        return None
    
    # Validate language compliance (no imperatives)
    if _contains_forbidden_language(explanation):
        logger.warning(
            f"Explanation for finding {finding.id} contains forbidden language, regenerating"
        )
        # Add emphasis and retry once
        retry_prompt = prompt + (
            "\n\nREMINDER: Use only descriptive language like 'this clause differs from...' "
            "Do NOT use imperative language like 'you should' or 'you must'."
        )
        messages = [{"role": "user", "content": retry_prompt}]
        response_text, tokens_used = await call_llm(messages, plain_text=True)
        explanation = response_text.strip()
    
    # Cache in database
    await db.execute(
        update(RiskFinding)
        .where(RiskFinding.id == finding.id)
        .values(
            explanation=explanation,
            explanation_generated_at=datetime.utcnow()
        )
    )
    await db.commit()
    
    logger.info(f"Generated explanation for finding {finding.id}")
    
    return explanation


def _build_explanation_prompt(finding: RiskFinding) -> str:
    """
    Build prompt for explanation generation.
    
    Emphasizes plain language, no legal advice, descriptive tone.
    """
    finding_type = "risky clause" if finding.finding_type == "risky_clause" else "missing clause"
    
    prompt = f"""Generate a plain-language explanation for this {finding_type} finding.

Finding Details:
- Type: {finding_type}
- Reason: {finding.reason}
- Severity: {finding.severity}
- Legal/Reference Basis: {finding.triggering_rule_or_corpus}

Requirements:
1. Write 2-4 sentences in plain English (8th-10th grade reading level)
2. Explain WHY this matters (legal and practical implications)
3. Use ONLY descriptive language:
   ✓ "This clause differs from standard practice because..."
   ✓ "This provision exceeds the legal limit of..."
   ✓ "Indian rental law typically requires..."
4. DO NOT use:
   ✗ Imperative language: "you should", "you must", "we recommend"
   ✗ Legal advice: "consult a lawyer", "hire an attorney"
   ✗ Technical jargon without explanation
5. Be factual and educational, not prescriptive

Generate the explanation:"""
    
    return prompt


def format_citation(triggering_rule_or_corpus: str) -> str:
    """
    Format legal citation from traced reference.
    
    CRITICAL: This is deterministic formatting, NOT LLM generation.
    This prevents citation hallucination - we only format what
    Stage 7 already traced to the knowledge base.
    
    Args:
        triggering_rule_or_corpus: Raw reference from Stage 7
    
    Returns:
        Formatted citation string
    
    Examples:
        "Model Tenancy Act 2021, Section 7(1)" 
        → "[Legal] Model Tenancy Act 2021, §7(1)"
        
        "Maharashtra Rent Control Act 1999, Section 11(2) (Maharashtra)"
        → "[Legal] Maharashtra Rent Control Act 1999, §11(2) (Maharashtra)"
        
        "Model Tenancy Act Section 13(1); Reference Example: Chennai"
        → "[Legal] Model Tenancy Act §13(1); [Reference] Chennai"
        
        "[Reference Example: Template] Clause text"
        → "[Reference] Template"
    """
    # Check for mixed citation (contains both legal and reference parts)
    if ";" in triggering_rule_or_corpus and "Reference Example" in triggering_rule_or_corpus:
        parts = triggering_rule_or_corpus.split(";")
        formatted_parts = []
        for part in parts:
            part = part.strip()
            if _is_legal_rule(part):
                formatted_parts.append(_format_legal_citation(part))
            else:
                formatted_parts.append(_format_corpus_citation(part))
        return "; ".join(formatted_parts)
    
    # Detect citation type
    if _is_legal_rule(triggering_rule_or_corpus):
        return _format_legal_citation(triggering_rule_or_corpus)
    else:
        return _format_corpus_citation(triggering_rule_or_corpus)


def display_citation(stored_formatted: str, triggering_rule_or_corpus: str) -> str:
    """
    Derive display-friendly citation label for UI.
    
    Rules:
    - If stored_formatted is non-empty, return it unchanged
    - Otherwise, format the trigger and return it (already cleaned by format_citation)
    - Truncate to 120 chars + '...' if needed
    - Return '' if trigger is empty
    
    Args:
        stored_formatted: Pre-computed formatted_citation from DB (may be empty)
        triggering_rule_or_corpus: Raw reference from Stage 7
    
    Returns:
        Citation label suitable for UI display (max 120 chars + '...')
    
    Examples:
        stored="[Legal] Act §7", trigger=X → "[Legal] Act §7"
        stored="", trigger="Act §7: Long text..." → "[Legal] Act §7"
        stored="", trigger="300 char sentence" → "First 120 chars..."
        stored="", trigger="" → ""
    """
    # If stored value exists, use it
    if stored_formatted:
        return stored_formatted
    
    # If trigger is empty, return empty
    if not triggering_rule_or_corpus:
        return ""
    
    # Format the trigger (this now returns clean labels without clause text)
    formatted = format_citation(triggering_rule_or_corpus)
    
    # Truncate if needed
    if len(formatted) <= 120:
        return formatted
    
    return formatted[:120] + '...'


def _is_legal_rule(reference: str) -> bool:
    """Detect if reference is a legal rule (vs corpus example)."""
    # Legal rules contain "Act" and "Section"
    return "Act" in reference and "Section" in reference


def _format_legal_citation(reference: str) -> str:
    """
    Format legal rule citation, extracting just the section reference.
    
    Pattern: "Act Name Section X(Y): Clause text..." → "[Legal] Act Name §X(Y)"
    Pattern: "Act Name Section X(Y)" → "[Legal] Act Name §X(Y)"
    """
    # If there's ": " it means clause text follows, extract just the legal reference part
    if ": " in reference:
        legal_part = reference.split(": ", 1)[0]
    else:
        legal_part = reference
    
    # Replace "Section" with section symbol (§)
    formatted = legal_part.replace("Section ", "§")
    
    # Add [Legal] prefix
    return f"[Legal] {formatted}"


def _format_corpus_citation(reference: str) -> str:
    """
    Format reference corpus citation.
    
    Patterns:
    - "[Reference Example: Template Name] Clause text..." 
      → "[Reference] Template Name"
    - "Reference Example: Template Name: Clause text..."
      → "[Reference] Template Name"
    - Otherwise: "[Reference] {reference}"
    """
    # Pattern 1: [Reference Example: Template] Clause text
    if reference.startswith("[Reference Example:") and "]" in reference:
        # Extract content between "[Reference Example:" and "]"
        start = len("[Reference Example:")
        end = reference.index("]")
        template_name = reference[start:end].strip()
        return f"[Reference] {template_name}"
    
    # Pattern 2: Reference Example: Template Name: Clause text
    if reference.startswith("Reference Example:"):
        # Remove "Reference Example:" prefix
        rest = reference[len("Reference Example:"):].strip()
        # If there's another ":", extract the part before it (template name)
        if ": " in rest:
            template_name = rest.split(": ", 1)[0].strip()
            return f"[Reference] {template_name}"
        # Otherwise use the whole rest
        return f"[Reference] {rest}"
    
    # Default: just add [Reference] prefix
    return f"[Reference] {reference}"


def _contains_forbidden_language(text: str) -> bool:
    """
    Check if explanation contains forbidden imperative/advice language.
    
    Returns True if forbidden patterns detected.
    """
    forbidden_patterns = [
        r'\byou should\b',
        r'\byou must\b',
        r'\byou need to\b',
        r'\bwe recommend\b',
        r'\bconsult a lawyer\b',
        r'\bhire an attorney\b',
        r'\bseek legal advice\b'
    ]
    
    text_lower = text.lower()
    
    for pattern in forbidden_patterns:
        if re.search(pattern, text_lower):
            logger.warning(f"Forbidden pattern detected: {pattern}")
            return True
    
    return False


async def generate_all_explanations(
    contract_id: int,
    db: AsyncSession
) -> int:
    """
    Generate explanations for all findings without valid explanations.
    
    Treats findings with invalid stored explanations (fail validate_explanation)
    as missing and regenerates them.
    
    Args:
        contract_id: Contract ID (INTEGER)
        db: Database session
    
    Returns:
        Count of newly generated explanations
        
    Raises:
        RuntimeError: If any findings lack valid explanations after generation
    """
    # Fetch ALL findings for this contract
    result = await db.execute(
        select(RiskFinding)
        .where(RiskFinding.contract_id == contract_id)
    )
    findings = result.scalars().all()
    
    if not findings:
        logger.info(f"No findings for contract {contract_id}")
        return 0
    
    # Identify findings needing explanation generation
    findings_to_generate = []
    for finding in findings:
        if finding.explanation is None:
            findings_to_generate.append(finding)
        else:
            # Validate stored explanation
            parsed = parse_explanation(finding.explanation)
            if not validate_explanation(parsed):
                logger.warning(f"Finding {finding.id} has invalid stored explanation, will regenerate")
                findings_to_generate.append(finding)
    
    if not findings_to_generate:
        logger.info(f"All explanations already valid for contract {contract_id}")
        return 0
    
    logger.info(f"Generating {len(findings_to_generate)} explanations for contract {contract_id}")
    
    # Generate explanations
    generated_count = 0
    failed_count = 0
    for finding in findings_to_generate:
        try:
            explanation = await generate_explanation(finding, db)
            if explanation:  # Only count if not None
                generated_count += 1
            else:
                failed_count += 1
        except Exception as e:
            logger.error(f"Failed to generate explanation for finding {finding.id}: {e}")
            failed_count += 1
            # Continue with other findings
    
    logger.info(f"Generated {generated_count} new explanations, {failed_count} failed")
    
    # Check if any findings still lack valid explanations
    if failed_count > 0:
        raise RuntimeError(f"{failed_count} findings lack valid explanations")
    
    return generated_count


async def get_contract_explanations(
    contract_id: int,
    db: AsyncSession,
    auto_generate: bool = True
) -> ContractExplanationsResponse:
    """
    Get all findings with explanations for a contract.
    
    Args:
        contract_id: Contract ID (INTEGER)
        db: Database session
        auto_generate: If True, generate missing explanations on-the-fly
    
    Returns:
        ContractExplanationsResponse with all findings
    """
    # Generate missing explanations if requested
    if auto_generate:
        await generate_all_explanations(contract_id, db)
    
    # Fetch all findings with explanations
    result = await db.execute(
        select(RiskFinding)
        .where(RiskFinding.contract_id == contract_id)
        .order_by(RiskFinding.severity.desc(), RiskFinding.created_at)
    )
    findings = result.scalars().all()
    
    # Separate by type and build responses
    risky_clauses = []
    missing_clauses = []
    
    for finding in findings:
        # Format citation (deterministic, no LLM)
        citation = format_citation(finding.triggering_rule_or_corpus)
        
        # Cache formatted citation if not already cached
        if not finding.formatted_citation or finding.formatted_citation != citation:
            await db.execute(
                update(RiskFinding)
                .where(RiskFinding.id == finding.id)
                .values(formatted_citation=citation)
            )
        
        if finding.finding_type == "risky_clause":
            # Fetch clause details
            clause = await _fetch_clause(finding.clause_id, db)
            
            risky_clauses.append(RiskyClauseExplanation(
                finding_id=str(finding.id),
                clause_id=finding.clause_id,
                clause_text=clause.text if clause else "",
                clause_number=clause.clause_id if clause else "",
                reason=finding.reason,
                severity=finding.severity,
                explanation=finding.explanation or "Explanation generation failed",
                formatted_citation=citation
            ))
        else:
            missing_clauses.append(MissingClauseExplanation(
                finding_id=str(finding.id),
                expected_clause_type=finding.expected_clause_type,
                reason=finding.reason,
                severity=finding.severity,
                explanation=finding.explanation or "Explanation generation failed",
                formatted_citation=citation
            ))
    
    await db.commit()
    
    # Build summary
    summary = {
        "total_risks": len(risky_clauses),
        "total_missing": len(missing_clauses),
        "high_severity": sum(1 for f in findings if f.severity == "high"),
        "medium_severity": sum(1 for f in findings if f.severity == "medium"),
        "low_severity": sum(1 for f in findings if f.severity == "low")
    }
    
    return ContractExplanationsResponse(
        contract_id=contract_id,
        risky_clauses=risky_clauses,
        missing_clauses=missing_clauses,
        summary=summary
    )


async def _fetch_clause(clause_id: int | None, db: AsyncSession) -> Clause | None:
    """Fetch clause details for risky clause findings."""
    if not clause_id:
        return None
    
    result = await db.execute(
        select(Clause).where(Clause.id == clause_id)
    )
    return result.scalar_one_or_none()
