"""
Explanation generation and citation formatting for ScanTract Stage 8.

Generates plain-language explanations for risk findings and formats
legal citations from traced references (no LLM hallucination).
"""

import re
from datetime import datetime
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession
import logging

from .llm_client import call_llm
from .models import ContractExplanationsResponse, RiskyClauseExplanation, MissingClauseExplanation
from ..db.models import RiskFinding, Clause

logger = logging.getLogger(__name__)


def parse_explanation(response_text: str) -> str | None:
    """
    Parse LLM response to extract plain-text explanation.
    
    Handles:
    - Plain text responses
    - JSON-wrapped responses with various key structures
    - Malformed JSON with trailing/leading fragments
    
    Args:
        response_text: Raw LLM response
    
    Returns:
        Cleaned explanation text or None if invalid
    """
    import json
    
    explanation = response_text.strip()
    
    # Reject if contains triple pipes (corruption indicator)
    if '|||' in explanation:
        logger.warning(f"Explanation contains '|||' corruption marker, rejecting")
        return None
    
    # Try to parse as JSON first
    if explanation.startswith('{'):
        try:
            parsed = json.loads(explanation)
            if isinstance(parsed, dict):
                # Extract text from ANY string value in dict
                # Priority: 'explanation' key, then first non-empty string value
                if 'explanation' in parsed and isinstance(parsed['explanation'], str):
                    explanation = parsed['explanation'].strip()
                else:
                    # Find first non-empty string value (skipping empty or whitespace-only)
                    for value in parsed.values():
                        if isinstance(value, str) and value.strip():
                            explanation = value.strip()
                            break
                    else:
                        # No valid string found
                        logger.warning(f"JSON dict has no valid string values: {list(parsed.keys())}")
                        return None
        except json.JSONDecodeError:
            # If JSON parsing fails, strip malformed JSON artifacts
            # Remove leading JSON fragments: {, {"key":, {", etc.
            # Pattern: opening brace, optional quotes/keys/colons, optional whitespace
            explanation = re.sub(r'^\{\s*("[^"]*"\s*:\s*)?["\s]*', '', explanation)
            # Remove trailing JSON fragments: }, ", etc.
            explanation = re.sub(r'["\s]*\}\s*$', '', explanation)
            explanation = explanation.strip()
    
    # Also strip leading } for malformed responses
    explanation = explanation.lstrip('}').strip()
    
    # Strip leading punctuation fragments from malformed JSON keys: ". ", ": ", etc.
    explanation = re.sub(r'^["\.\s:]+', '', explanation)
    
    return explanation


def validate_explanation(explanation: str | None) -> bool:
    """
    Validate parsed explanation meets quality criteria.
    
    Args:
        explanation: Parsed explanation text
    
    Returns:
        True if valid, False otherwise
    """
    # Validate length - reject if too short, just braces/null, or over 2000 chars
    if not explanation or len(explanation.strip()) < 20 or len(explanation) > 2000 or explanation.strip() in ["{}", "null", "{\n\n}"]:
        return False
    return True


async def generate_explanation(
    finding: RiskFinding,
    db: AsyncSession
) -> str:
    """
    Generate plain-language explanation for a risk finding.
    
    Args:
        finding: RiskFinding from database
        db: Database session
    
    Returns:
        Plain-language explanation (2-4 sentences)
    
    Note:
        Citation is NOT generated by LLM - formatted separately
        from existing triggering_rule_or_corpus field.
    """
    # Build prompt for explanation
    prompt = _build_explanation_prompt(finding)
    
    # Call LLM (provider-agnostic via call_llm) - request plain text
    messages = [{"role": "user", "content": prompt}]
    response_text, tokens_used = await call_llm(messages, plain_text=True)
    
    # Parse and validate using extracted functions
    explanation = parse_explanation(response_text)
    
    if not validate_explanation(explanation):
        logger.warning(
            f"Generated explanation is invalid (len={len(explanation) if explanation else 0}): "
            f"'{explanation[:50] if explanation else 'None'}'"
        )
        # Don't cache invalid explanation, leave it NULL
        return None
    
    # Validate language compliance (no imperatives)
    if _contains_forbidden_language(explanation):
        logger.warning(
            f"Explanation for finding {finding.id} contains forbidden language, regenerating"
        )
        # Add emphasis and retry once
        retry_prompt = prompt + (
            "\n\nREMINDER: Use only descriptive language like 'this clause differs from...' "
            "Do NOT use imperative language like 'you should' or 'you must'."
        )
        messages = [{"role": "user", "content": retry_prompt}]
        response_text, tokens_used = await call_llm(messages, plain_text=True)
        explanation = response_text.strip()
    
    # Cache in database
    await db.execute(
        update(RiskFinding)
        .where(RiskFinding.id == finding.id)
        .values(
            explanation=explanation,
            explanation_generated_at=datetime.utcnow()
        )
    )
    await db.commit()
    
    logger.info(f"Generated explanation for finding {finding.id}")
    
    return explanation


def _build_explanation_prompt(finding: RiskFinding) -> str:
    """
    Build prompt for explanation generation.
    
    Emphasizes plain language, no legal advice, descriptive tone.
    """
    finding_type = "risky clause" if finding.finding_type == "risky_clause" else "missing clause"
    
    prompt = f"""Generate a plain-language explanation for this {finding_type} finding.

Finding Details:
- Type: {finding_type}
- Reason: {finding.reason}
- Severity: {finding.severity}
- Legal/Reference Basis: {finding.triggering_rule_or_corpus}

Requirements:
1. Write 2-4 sentences in plain English (8th-10th grade reading level)
2. Explain WHY this matters (legal and practical implications)
3. Use ONLY descriptive language:
   ✓ "This clause differs from standard practice because..."
   ✓ "This provision exceeds the legal limit of..."
   ✓ "Indian rental law typically requires..."
4. DO NOT use:
   ✗ Imperative language: "you should", "you must", "we recommend"
   ✗ Legal advice: "consult a lawyer", "hire an attorney"
   ✗ Technical jargon without explanation
5. Be factual and educational, not prescriptive

Generate the explanation:"""
    
    return prompt


def format_citation(triggering_rule_or_corpus: str) -> str:
    """
    Format legal citation from traced reference.
    
    CRITICAL: This is deterministic formatting, NOT LLM generation.
    This prevents citation hallucination - we only format what
    Stage 7 already traced to the knowledge base.
    
    Args:
        triggering_rule_or_corpus: Raw reference from Stage 7
    
    Returns:
        Formatted citation string
    
    Examples:
        "Model Tenancy Act 2021, Section 7(1)" 
        → "[Legal] Model Tenancy Act 2021, §7(1)"
        
        "Maharashtra Rent Control Act 1999, Section 11(2) (Maharashtra)"
        → "[Legal] Maharashtra Rent Control Act 1999, §11(2) (Maharashtra)"
        
        "Standard practice - fair deposit terms"
        → "[Reference] Standard practice - fair deposit terms"
    """
    # Detect citation type
    if _is_legal_rule(triggering_rule_or_corpus):
        return _format_legal_citation(triggering_rule_or_corpus)
    else:
        return _format_corpus_citation(triggering_rule_or_corpus)


def _is_legal_rule(reference: str) -> bool:
    """Detect if reference is a legal rule (vs corpus example)."""
    # Legal rules contain "Act" and "Section"
    return "Act" in reference and "Section" in reference


def _format_legal_citation(reference: str) -> str:
    """
    Format legal rule citation.
    
    Pattern: "Act Name YEAR, Section X(Y)" → "[Legal] Act Name YEAR, §X(Y)"
    """
    # Replace "Section" with section symbol (§)
    formatted = reference.replace("Section ", "§")
    
    # Add [Legal] prefix
    return f"[Legal] {formatted}"


def _format_corpus_citation(reference: str) -> str:
    """
    Format reference corpus citation.
    
    Pattern: "Label - description" → "[Reference] Label - description"
    """
    return f"[Reference] {reference}"


def _contains_forbidden_language(text: str) -> bool:
    """
    Check if explanation contains forbidden imperative/advice language.
    
    Returns True if forbidden patterns detected.
    """
    forbidden_patterns = [
        r'\byou should\b',
        r'\byou must\b',
        r'\byou need to\b',
        r'\bwe recommend\b',
        r'\bconsult a lawyer\b',
        r'\bhire an attorney\b',
        r'\bseek legal advice\b'
    ]
    
    text_lower = text.lower()
    
    for pattern in forbidden_patterns:
        if re.search(pattern, text_lower):
            logger.warning(f"Forbidden pattern detected: {pattern}")
            return True
    
    return False


async def generate_all_explanations(
    contract_id: int,
    db: AsyncSession
) -> int:
    """
    Generate explanations for all findings without cached explanations.
    
    Args:
        contract_id: Contract ID (INTEGER)
        db: Database session
    
    Returns:
        Count of newly generated explanations
    """
    # Fetch findings without explanations
    result = await db.execute(
        select(RiskFinding)
        .where(RiskFinding.contract_id == contract_id)
        .where(RiskFinding.explanation.is_(None))
    )
    findings = result.scalars().all()
    
    if not findings:
        logger.info(f"All explanations already cached for contract {contract_id}")
        return 0
    
    logger.info(f"Generating {len(findings)} explanations for contract {contract_id}")
    
    # Generate explanations
    generated_count = 0
    failed_count = 0
    for finding in findings:
        try:
            explanation = await generate_explanation(finding, db)
            if explanation:  # Only count if not None
                generated_count += 1
            else:
                failed_count += 1
        except Exception as e:
            logger.error(f"Failed to generate explanation for finding {finding.id}: {e}")
            failed_count += 1
            # Continue with other findings
    
    logger.info(f"Generated {generated_count} new explanations, {failed_count} failed")
    
    return generated_count


async def get_contract_explanations(
    contract_id: int,
    db: AsyncSession,
    auto_generate: bool = True
) -> ContractExplanationsResponse:
    """
    Get all findings with explanations for a contract.
    
    Args:
        contract_id: Contract ID (INTEGER)
        db: Database session
        auto_generate: If True, generate missing explanations on-the-fly
    
    Returns:
        ContractExplanationsResponse with all findings
    """
    # Generate missing explanations if requested
    if auto_generate:
        await generate_all_explanations(contract_id, db)
    
    # Fetch all findings with explanations
    result = await db.execute(
        select(RiskFinding)
        .where(RiskFinding.contract_id == contract_id)
        .order_by(RiskFinding.severity.desc(), RiskFinding.created_at)
    )
    findings = result.scalars().all()
    
    # Separate by type and build responses
    risky_clauses = []
    missing_clauses = []
    
    for finding in findings:
        # Format citation (deterministic, no LLM)
        citation = format_citation(finding.triggering_rule_or_corpus)
        
        # Cache formatted citation if not already cached
        if not finding.formatted_citation or finding.formatted_citation != citation:
            await db.execute(
                update(RiskFinding)
                .where(RiskFinding.id == finding.id)
                .values(formatted_citation=citation)
            )
        
        if finding.finding_type == "risky_clause":
            # Fetch clause details
            clause = await _fetch_clause(finding.clause_id, db)
            
            risky_clauses.append(RiskyClauseExplanation(
                finding_id=str(finding.id),
                clause_id=finding.clause_id,
                clause_text=clause.text if clause else "",
                clause_number=clause.clause_id if clause else "",
                reason=finding.reason,
                severity=finding.severity,
                explanation=finding.explanation or "Explanation generation failed",
                formatted_citation=citation
            ))
        else:
            missing_clauses.append(MissingClauseExplanation(
                finding_id=str(finding.id),
                expected_clause_type=finding.expected_clause_type,
                reason=finding.reason,
                severity=finding.severity,
                explanation=finding.explanation or "Explanation generation failed",
                formatted_citation=citation
            ))
    
    await db.commit()
    
    # Build summary
    summary = {
        "total_risks": len(risky_clauses),
        "total_missing": len(missing_clauses),
        "high_severity": sum(1 for f in findings if f.severity == "high"),
        "medium_severity": sum(1 for f in findings if f.severity == "medium"),
        "low_severity": sum(1 for f in findings if f.severity == "low")
    }
    
    return ContractExplanationsResponse(
        contract_id=contract_id,
        risky_clauses=risky_clauses,
        missing_clauses=missing_clauses,
        summary=summary
    )


async def _fetch_clause(clause_id: int | None, db: AsyncSession) -> Clause | None:
    """Fetch clause details for risky clause findings."""
    if not clause_id:
        return None
    
    result = await db.execute(
        select(Clause).where(Clause.id == clause_id)
    )
    return result.scalar_one_or_none()
